[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["SÃ©bastien Eustace <sebastien@eustace.io>"]

[tool.poetry.dependencies]
python = ">=3.6,<4.0"
azure-nspkg = "^3.0.2"

[tool.poetry.dev-dependencies]
pytest = "^3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"